
package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author braya
 */
public class Menu extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_menu;

    public Menu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        this.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_administrador = new javax.swing.JMenu();
        Item_nuevo_admin = new javax.swing.JMenuItem();
        Item_gestionar_admin = new javax.swing.JMenuItem();
        jMenu_producto = new javax.swing.JMenu();
        Item_nuevo_producto = new javax.swing.JMenuItem();
        Item_gestionar_producto = new javax.swing.JMenuItem();
        Item_actualizar_stock = new javax.swing.JMenuItem();
        jMenu_cliente = new javax.swing.JMenu();
        Item_nuevo_cliente = new javax.swing.JMenuItem();
        Item_gestionar_cliente = new javax.swing.JMenuItem();
        jMenu_Categoria = new javax.swing.JMenu();
        Item_nueva_categoria = new javax.swing.JMenuItem();
        Item_gestionar_categoria = new javax.swing.JMenuItem();
        jMenu_facturar = new javax.swing.JMenu();
        Item_nueva_venta = new javax.swing.JMenuItem();
        Item_gestionar_venta = new javax.swing.JMenuItem();
        jMenu_reportes = new javax.swing.JMenu();
        Item_reportes_clientes = new javax.swing.JMenuItem();
        Item_reportes_categorias = new javax.swing.JMenuItem();
        Item_reportes_productos = new javax.swing.JMenuItem();
        Item_reportes_ventas = new javax.swing.JMenuItem();
        jMenu_historial = new javax.swing.JMenu();
        Item_ver_historial = new javax.swing.JMenuItem();
        jMenu_cerrar_sesion = new javax.swing.JMenu();
        Item_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu_administrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu_administrador.setText("Administrador");
        jMenu_administrador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu_administrador.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_nuevo_admin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Item_nuevo_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        Item_nuevo_admin.setText("Nuevo Administrador");
        Item_nuevo_admin.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_administrador.add(Item_nuevo_admin);

        Item_gestionar_admin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Item_gestionar_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        Item_gestionar_admin.setText("Gestionar Administrador");
        Item_gestionar_admin.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu_administrador.add(Item_gestionar_admin);

        jMenuBar1.add(jMenu_administrador);

        jMenu_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu_producto.setText("Producto");
        jMenu_producto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_producto.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_nuevo_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_nuevo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        Item_nuevo_producto.setText("Nuevo Producto");
        jMenu_producto.add(Item_nuevo_producto);

        Item_gestionar_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_gestionar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        Item_gestionar_producto.setText("Gestionar Productos");
        jMenu_producto.add(Item_gestionar_producto);

        Item_actualizar_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        Item_actualizar_stock.setText("Actualizar Stock");
        jMenu_producto.add(Item_actualizar_stock);

        jMenuBar1.add(jMenu_producto);

        jMenu_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu_cliente.setText("Cliente");
        jMenu_cliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_cliente.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_nuevo_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_nuevo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        Item_nuevo_cliente.setText("Nuevo Cliente");
        jMenu_cliente.add(Item_nuevo_cliente);

        Item_gestionar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_gestionar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Item_gestionar_cliente.setText("Gestionar Clientes");
        jMenu_cliente.add(Item_gestionar_cliente);

        jMenuBar1.add(jMenu_cliente);

        jMenu_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu_Categoria.setText("Categoria");
        jMenu_Categoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_Categoria.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_nueva_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        Item_nueva_categoria.setText("Nueva Categoria");
        jMenu_Categoria.add(Item_nueva_categoria);

        Item_gestionar_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_gestionar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        Item_gestionar_categoria.setText("Gestionar Categorias");
        jMenu_Categoria.add(Item_gestionar_categoria);

        jMenuBar1.add(jMenu_Categoria);

        jMenu_facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu_facturar.setText("Facturar");
        jMenu_facturar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_facturar.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_nueva_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_nueva_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        Item_nueva_venta.setText("Nueva Venta");
        jMenu_facturar.add(Item_nueva_venta);

        Item_gestionar_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_gestionar_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        Item_gestionar_venta.setText("Gestionar Ventas");
        jMenu_facturar.add(Item_gestionar_venta);

        jMenuBar1.add(jMenu_facturar);

        jMenu_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu_reportes.setText("Reportes");
        jMenu_reportes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_reportes.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_reportes_clientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_reportes_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Item_reportes_clientes.setText("Reportes Clientes");
        jMenu_reportes.add(Item_reportes_clientes);

        Item_reportes_categorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_reportes_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Item_reportes_categorias.setText("Reportes Categorias");
        jMenu_reportes.add(Item_reportes_categorias);

        Item_reportes_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_reportes_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Item_reportes_productos.setText("Reportes Productos");
        jMenu_reportes.add(Item_reportes_productos);

        Item_reportes_ventas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_reportes_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Item_reportes_ventas.setText("Reportes Ventas");
        jMenu_reportes.add(Item_reportes_ventas);

        jMenuBar1.add(jMenu_reportes);

        jMenu_historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu_historial.setText("Historial");
        jMenu_historial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_historial.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_ver_historial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_ver_historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        Item_ver_historial.setText("Ver Historial");
        jMenu_historial.add(Item_ver_historial);

        jMenuBar1.add(jMenu_historial);

        jMenu_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu_cerrar_sesion.setText("Cerrar Sesion");
        jMenu_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu_cerrar_sesion.setPreferredSize(new java.awt.Dimension(150, 50));

        Item_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Item_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        Item_cerrar_sesion.setText("Cerrar Sesion");
        jMenu_cerrar_sesion.add(Item_cerrar_sesion);

        jMenuBar1.add(jMenu_cerrar_sesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Item_actualizar_stock;
    private javax.swing.JMenuItem Item_cerrar_sesion;
    private javax.swing.JMenuItem Item_gestionar_admin;
    private javax.swing.JMenuItem Item_gestionar_categoria;
    private javax.swing.JMenuItem Item_gestionar_cliente;
    private javax.swing.JMenuItem Item_gestionar_producto;
    private javax.swing.JMenuItem Item_gestionar_venta;
    private javax.swing.JMenuItem Item_nueva_categoria;
    private javax.swing.JMenuItem Item_nueva_venta;
    private javax.swing.JMenuItem Item_nuevo_admin;
    private javax.swing.JMenuItem Item_nuevo_cliente;
    private javax.swing.JMenuItem Item_nuevo_producto;
    private javax.swing.JMenuItem Item_reportes_categorias;
    private javax.swing.JMenuItem Item_reportes_clientes;
    private javax.swing.JMenuItem Item_reportes_productos;
    private javax.swing.JMenuItem Item_reportes_ventas;
    private javax.swing.JMenuItem Item_ver_historial;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Categoria;
    private javax.swing.JMenu jMenu_administrador;
    private javax.swing.JMenu jMenu_cerrar_sesion;
    private javax.swing.JMenu jMenu_cliente;
    private javax.swing.JMenu jMenu_facturar;
    private javax.swing.JMenu jMenu_historial;
    private javax.swing.JMenu jMenu_producto;
    private javax.swing.JMenu jMenu_reportes;
    // End of variables declaration//GEN-END:variables
}
